name = "weather-cf-workers"
main = "src/index.ts"
compatibility_date = "2022-09-11"


# Define top-level environment variables
# under the `[vars]` block using
# the `key = "value"` format
[vars]
OPENWEATHER_API_URL = "https://api.openweathermap.org/data/2.5"


# The necessary secrets are:
# - OPENWEATHER_API_KEY
# Run `echo <secret-content> | wrangler secret put OPENWEATHER_API_KEY` for each of these